### ISSUE TITLE
Password Protect

### ISSUE THREAD

**Issue by EltonRst** [cangelis/php-pdf#11]
Can i protect my PDF with password ?
I need a demo

**Comment by cangelis** [comment]
I do not think wkhtmltopdf supports this feature. If wkhtmltopdf supports this the library will also.

**Comment by EltonRst** [comment]
Thanks, I'm developing a library to use with qpdf

https://github.com/EltonRst/qpdf-php

QPDF Library: https://github.com/qpdf/qpdf
