### ISSUE TITLE
Not Found on Windows

### ISSUE THREAD

**Issue by EltonRst** [cangelis/php-pdf#12]
Fatal error: in  vendor\cangelis\pdf\src\CanGelis\PDF\PDF.php on line 154

```
$pdf = new PDF("C:\DEV\wkhtmltopdf\bin\wkhtmltopdf.exe");
			
$pdf->marginTop('5mm');
$pdf->marginRight('5mm');
$pdf->marginBottom('5mm');
$pdf->marginLeft('5mm');
						
header('Content-Type: application/pdf');
header('Content-Disposition: inline; filename=test.pdf');
echo $pdf->loadHTML("<h1>HELLO WORLD</h1>")->get();
```

**Comment by cangelis** [comment]
Are you sure the wkhtmltopdf executable exists in the folder you provided?

**Comment by EltonRst** [comment]
Yes I'm sure.

I changed the installation path several times, but nothing solved.

![image](https://cloud.githubusercontent.com/assets/15981323/24829985/43e10582-1c53-11e7-97d1-27e1c71f1b90.png)

I use PHP with Microsoft IIS 10

![image](https://cloud.githubusercontent.com/assets/15981323/24830022/d85ae444-1c53-11e7-8d06-84e868661cdf.png)

**Comment by EltonRst** [comment]
Sorry for the image, in code it is: `C:\DEV\wkhtmltopdf\bin\wkhtmltopdf.exe`
But the correct one is `D:\DEV\wkhtmltopdf\bin\wkhtmltopdf.exe`
I just confused the units` C:\` and `D:\` , but it still does not work.

In windows, now i using:  https://github.com/mikehaertl/phpwkhtmltopdf
This library has the option to use PHP `exec()` or PHP `proc_open()`

`proc_open()` have a note for Windows

![image](https://cloud.githubusercontent.com/assets/15981323/24925811/d5d541c8-1ecf-11e7-8ad6-931c5d0330af.png)


As you can see in: https://github.com/mikehaertl/php-shellcommand/blob/master/src/Command.php
Lines: 302 and 314

Which makes it possible to run on Windows or Linux.
