### ISSUE TITLE
When Creating pdf i am getting error

### ISSUE THREAD

**Issue by rajanishtimes** [cangelis/php-pdf#9]
PDF could not be created: "sh: 1: \/tmp\/4478858306fc097ae7.html: Permission denied\n"I am here

Also What command to pass constructor

/**
	 * Initialize temporary file names and folders
	 *
	 * @param $cmd
	 * @param null $tmpFolder
	 */
	public function __construct($cmd, $tmpFolder = null)
	{
		$this->cmd = $cmd;

		$this->fileName = uniqid(rand(0, 99999));

		if (is_null($tmpFolder))
		{
			$this->folder = sys_get_temp_dir();
		}
		else
		{
			$this->folder = $tmpFolder;
		}

	}

**Comment by cangelis** [comment]
Looks like you do not have permission to write temporary folder.
